### ISSUE TITLE
Tiktok - Validate the Tiktok "Account Name" field

### ISSUE THREAD

**Issue by aidenmitchell** [kolbyg/Data-Hoarder-Download-Utility#3]
In the Tiktok Account Name field, if a user puts in *@username* instead of just *username* it will fail, because yt-dlp cannot handle the *@username* format. Maybe check for any @ symbols and remove them, or throw an error.

**Comment by kolbyg** [comment]
Added a method to remove illegal characters from the username when adding them to the watched users list. This applies to IG and TT. So far only @ is removed.

**Comment by kolbyg** [comment]
Fixed in v0.12
