### ISSUE TITLE
All platforms - Whitespace users/urls are allowed to be added to the list

### ISSUE THREAD

**Issue by aidenmitchell** [kolbyg/Data-Hoarder-Download-Utility#4]
![image](https://user-images.githubusercontent.com/30846409/148877003-0880e9f6-efba-4fe7-b313-c24b2600b102.png)
Check for only whitespace and throw an error.

**Comment by aidenmitchell** [comment]
This seems to be an issue with all platforms.

**Comment by kolbyg** [comment]
Fixed in v0.12
